import "@/assets/styles/index.css";
import { BaseLayout } from "@/layouts/Base";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { PropsWithChildren } from "react";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = PropsWithChildren & {};

function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en" className="size-full">
      <body className={`${dmSans.variable} size-full font-sans antialiased`}>
        <BaseLayout>{children}</BaseLayout>
      </body>
    </html>
  );
}

export default RootLayout;
